# Default variables for Unbound caching DNS role
---
unbound_packages:
  - unbound

unbound_service_name: unbound

# Template source and destination
unbound_config_template: server.conf.j2
unbound_config_dest: /etc/unbound/conf.d/ansible_generated.conf
unbound_config_owner: root
unbound_config_group: unbound
unbound_config_mode: "0644"
unbound_config_setype: named_conf_t

# Firewalld
unbound_manage_firewall: true
unbound_firewalld_service: dns

# Template variables
unbound_allowed_networks:
  - "172.25.0.0/6"
  - "192.168.62.0/24"
unbound_insecure_domain: "pvt.example.com"
unbound_forwarder_ip: "172.25.254.254"


