---
- name: Restart named
  ansible.builtin.service:
    name: "{{ bind_service_name }}"
    state: restarted

- name: Reload named
  ansible.builtin.service:
    name: "{{ bind_service_name }}"
    state: reloaded


